feat!: GUI via pyside6
afq984/ilmsdump pull request #19
Opened 2020-12-20 20:30 UTC by JackKuo-tw

簡陋的 GUI 介面，可以正常執行。
- 小問題：
  - 在下載時尚未使用多執行序因此會導致卡死。
  - 目前我無法成功在 macOS Big Sur 上面完整打包...

給個初稿，不一定要 merge，也可以開新 branch 來發展這套 :)

2020-12-21 00:29 UTC, afq984 reviewed
> 在下載時尚未使用多執行序因此會導致卡死

可能要把 asyncio 的 event loop 丟到 QThread 裡面去跑？
我沒試過不知道會不會發生怪怪的問題

> 目前我無法成功在 macOS Big Sur 上面完整打包...

你希望的打包方式是什麼？我會想把他變成一個 package 放在 `ilmsdump/gui/` 下面，然後給他一個 [gui_scripts](https://packaging.python.org/specifications/entry-points/#use-for-scripts) 的 entry point
(disclaimer: 我沒用過 macOS)
如果要這樣放的話，可以參考 (packaging) 的 review comment

---

我覺得 CI & 檔案位置調整好就能 merge 到 gui-dev 之類的 branch；
threading / asyncio 的問體搞定就可以上 main branch 了

歡迎討論~

2020-12-21 00:29 UTC, afq984 commented on setup.py
> +            'pyside6',
有些平台可能會沒辦法那麼好裝 pyside；extra_requires 裡面另外開一個 
```
'gui': [
 'pyside6',
],
```
給他

2020-12-21 00:29 UTC, afq984 commented on gui.py
> +    global courses
這裡應該不需要設成 global variable
`asyncio.run_until_complete` 會把結果傳回去 caller 那邊

2020-12-21 00:29 UTC, afq984 commented on gui.py
> +from PySide2.QtUiTools import QUiLoader
(packaging)

move to `ilmsdump/gui/__init__.py`

2020-12-21 00:29 UTC, afq984 commented on ilmsdump.ui
> +<?xml version="1.0" encoding="UTF-8"?>
(packaging)

move inside `ilmsdump/gui/`

setup.py would need package_data=XXX to include this file

2020-12-21 05:52 UTC, JackKuo-tw commented
我的打包是指輸出成 `.exe`, `.app` 等，讓使用者可以直接執行。
放了 QThread 的程式碼，但是沒執行，因為會遇到問題，還沒解：
```
Cannot create children for a parent that is in a different thread
```
目前維持下載時 GUI 卡死，等待有心人士幫解～～

感謝 code review，大大的程式功力真是厲害！
有問題還請不吝指教

2020-12-21 10:07 UTC, afq984 requested changes
Thread 我自己有一些想法，可以 merge 之後再處理
剩下一些小問題

2020-12-21 10:07 UTC, afq984 commented on ilmsdump/gui/__init__.py
> +        pass
TypeError 是 `TypeError: object list can't be used in 'await' expression` 嗎？
```suggestion
    courses = [c async for c in client.get_enrolled_courses()]
```

2020-12-21 10:07 UTC, afq984 commented on ilmsdump/gui/__init__.py
> +    form = Form("ilmsdump.ui")
這個路徑如果 `ilmsdump.ui` 不在現在的資料夾讀得到嗎？

2020-12-21 10:07 UTC, afq984 commented on ilmsdump/gui/__init__.py
> +        super(Form, self).__init__(parent)
```suggestion
        super().__init__(parent)
```

2020-12-21 10:07 UTC, afq984 commented on ilmsdump/gui/__init__.py
> +    def log(self, text):
好像很多地方都會 self.log(f'... {datetime.now().strftime(...)}')
```suggestion
    def log(self, text, *, with_timestamp=False):
```

2020-12-21 18:37 UTC, JackKuo-tw commented on ilmsdump/gui/__init__.py
> +        pass
沒錯，被抓包XD，我沒詳細去看原因，一個 workaround

2020-12-21 18:46 UTC, JackKuo-tw commented on ilmsdump/gui/__init__.py
> +    form = Form("ilmsdump.ui")
對欸不行 😱，請問有什麼推薦的方式嗎？
我的想法是從最外部放一個主程式去呼叫 CLI 與 GUI，這樣位置就會相對固定。
若不透過主程式而是直接呼叫 GUI 程式，使用 `__file__` 方式去抓路徑也行。

2020-12-21 18:48 UTC, JackKuo-tw commented on ilmsdump/gui/__init__.py
> +    def log(self, text):
這另外抽出成一個 function 沒問題！

2020-12-21 19:04 UTC, JackKuo-tw commented
@afq984 請教一下，`flake8` 的警告訊息在你的檔案中怎麼不會被檢查到？
看 `.flake8` 裡面也沒有特別排除
```
 W606 'async' and 'await' are reserved keywords starting with Python 3.7
```

2020-12-21 19:04 UTC, afq984 commented on ilmsdump/gui/__init__.py
> +    form = Form("ilmsdump.ui")
之後如果打算要包成單一執行檔可能要用一些比較神奇的方法...
https://setuptools.readthedocs.io/en/latest/pkg_resources.html#basic-resource-access

2020-12-21 19:18 UTC, afq984 commented
> @afq984 請教一下，`flake8` 的警告訊息在你的檔案中怎麼不會被檢查到？
> 看 `.flake8` 裡面也沒有特別排除
> 
> ```
>  W606 'async' and 'await' are reserved keywords starting with Python 3.7
> ```

我不太確定你覺得哪裡沒檢查到

他這句話的意思是說從 python 3.7 開始 `async` 跟 `await` 變成正式 keyword 了，不能做為 identifier 使用。
你之前出現這個錯誤我猜是因為 flake8 以為你的
```
await [... async for ...]
```
是想當變數來 `__getitem__`。
舉例來說，在 python 3.6，以下是合法的：
```
await = [3, 4, 5]
await [1]
```

2020-12-22 03:43 UTC, JackKuo-tw commented on ilmsdump/gui/__init__.py
> +    form = Form("ilmsdump.ui")
我有嘗試 pyinstaller、py2app、cx_Freeze 都失敗，可能是我的 Qt 版本對不上。
fbs 的話似乎要改寫一些東西還沒試完。
這幾個工具你也可以試試看，印象中幾年前玩過 PySide2 可以用 cx_Freeze 成功打包。

2020-12-22 03:44 UTC, JackKuo-tw commented on ilmsdump/gui/__init__.py
> +        pass
fixed

2020-12-22 12:32 UTC, afq984 approved these changes

2020-12-22 12:35 UTC, merged

2020-12-22 13:31 UTC, afq984 commented
@JackKuo-tw 我有空會先看 UI freeze 跟 application packaging 的部分

有甚麼你覺得發布之前需要做好的事情就再開 issue